services:
  mongo1:
    image: mongo:4.4
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    volumes:
      - mongo1:/data/db
    ports:
      - 30001:30001
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"mongo1:30001\"},{_id:1,host:\"mongo2:30002\"},{_id:2,host:\"mongo3:30003\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    depends_on:
      - mongo2
      - mongo3
    logging:
      driver: none # disable logging
  mongo2:
    image: mongo:4.4
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    volumes:
      - mongo2:/data/db
    ports:
      - 30002:30002
    logging:
      driver: none # disable logging
  mongo3:
    image: mongo:4.4
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    volumes:
      - mongo3:/data/db
    ports:
      - 30003:30003
    logging:
      driver: none # disable logging

  redis:
    image: "redis"
    volumes:
      - redis:/data

  redisCommander:
    image: "rediscommander/redis-commander"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    init: true
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    env_file:
      - path: .env
        required: true
    ports:
      - '${API_PORT}:5000'
    command: sh -c "pnpm --filter api prisma db push --skip-generate && pnpm --filter api start:debug"
    depends_on: 
      - mongo1
      - mongo2
      - mongo3
      - redis

volumes:
  mongo1:
  mongo2:
  mongo3:
  redis:
